# Generated by Django 2.0.6 on 2018-06-14 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('idCandidate', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Elections',
            fields=[
                ('idElection', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('voterType', models.CharField(max_length=200)),
                ('electorType', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('idLogin', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('matricule', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('activationLink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('secondName', models.CharField(max_length=200)),
                ('userType', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('creationDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('idVoting', models.AutoField(primary_key=True, serialize=False)),
                ('Election_idElection', models.CharField(max_length=200)),
                ('User_idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.User')),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='User_idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.User'),
        ),
        migrations.AddField(
            model_name='elections',
            name='User_idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.User'),
        ),
    ]
