# Generated by Django 2.0.6 on 2018-06-24 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0004_auto_20180622_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('idPosition', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('election_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voting.Elections')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='position',
        ),
        migrations.AddField(
            model_name='candidate',
            name='election_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voting.Elections'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voting.Position'),
        ),
    ]
