# Generated by Django 2.0.6 on 2018-06-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20180624_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='election_id',
            new_name='election',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='position_id',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='election_id',
            new_name='election',
        ),
    ]
