# Generated by Django 2.0.6 on 2018-06-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20180624_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.CharField(default='Nges', max_length=100),
        ),
    ]
