# Generated by Django 2.0.6 on 2018-06-24 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20180624_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='Election_idElection',
        ),
        migrations.AddField(
            model_name='voting',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voting.Candidate'),
        ),
    ]
