# Generated by Django 2.0.6 on 2018-06-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20180624_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='User_idUser',
            new_name='user',
        ),
    ]
